#!/bin/bash

# disable output if glob not matched
shopt -s nullglob

# init arrays
extensions=( .png .jpg .jpeg .webp .PNG .JPG .JPEG .WEBP )
covernames=({Cover,cover,Cover1,cover1,Front,front}.{png,jpg,jpeg,webp,PNG,JPG,JPEG,WEBP})
previous_cover_file=""

same_cover(){
	# cover path is the same
	if [ "$previous_cover_file" == "$cover_file" ]; then
		# separate file
		if [ "$cover_file" != '/tmp/embedded_cover.jpg' ]; then
			return 0;
		# ever extracted before, previous cover was embedded and new size is the same
		elif [ -f /tmp/embedded_cover.jpg ] && \
				[ "$previous_cover_file" == '/tmp/embedded_cover.jpg' ] && \
				[ $(du -b -s /tmp/embedded_cover.jpg | cut -f1) \
			   	== $(du -b -s /tmp/new_embedded_cover.jpg | cut -f1) ]; then
			return 0
		fi
	fi
	return 1
}

get_cover(){
	cover_file=""
	# search for well-named covers
	for covername in ${covernames[*]}; do
		if [ -f "$path$covername" ]; then
			cover_file="$path$covername"
			echo $(date '+%H:%M:%S') found artwork in: "$cover_file"
			return 0
		fi
	done
	# if not found, search for any covers as files
	# this part is retarded
	potential_covers=""
	for ext in ${extensions[*]}; do
		potential_covers=( "$path"*"$ext" )
		if (( ${#potential_covers[@]} )); then
			cover_file=${potential_covers[0]}
			echo $(date '+%H:%M:%S') found artwork in: "$cover_file"
			return 0
		fi
	done
	# embedded cover exists
	if ( kid3-cli -c get "$track_file" | grep -q Picture ); then
		echo $(date '+%H:%M:%S') found embedded artwork in: "$track_file"
		kid3-cli -c 'get picture:/tmp/new_embedded_cover.jpg' "$track_file"
		cover_file="/tmp/embedded_cover.jpg"
		return 0
	fi

	echo $(date '+%H:%M:%S') "fix needed: \"$track_file\""
	echo $(date '+%H:%M:%S') "fix needed: \"$track_file\"" >> ~/broken.txt
	return 1
}

set_wallpaper(){
		# transformations for better visuals
		magick  \
			\( "$cover_file" -resize $resolution^ -gravity Center -crop $resolution+0+0 -blur 0x12 -level 0%,180% +repage \) \
			\( "$cover_file" -resize $subresolution -background none -gravity south -extent $resolution \) \
			-layers Flatten -define png:compression-level=0 /tmp/background.png
		# set wallpaper
		feh --no-fehbg --bg-center "/tmp/background.png"
}

# not enough arguments given
if [ -z "$2" ]; then
	echo "	Usage:
	$0 fallback/image bar_height
	e.g.: $0 \$HOME/Pictures/Wallpapers/GiTS/1.png 24"
	exit 1
fi
# file doesn't exist
if ! [ -f "$1" ]; then
	echo couldn\'t open \""$1"\"
	exit 1
fi

resolution=$( xdpyinfo | grep -P -o '[0-9]*x[0-9]* pixels' | cut -f1 -d' ' )
subresolution=${resolution%x*}x$(( ${resolution##*x} - $2 ))
musicpath=$( grep 'music_directory' $HOME/.mpd/mpd.conf | cut -f2 -d' ' | sed "s+\"++g; s+~+$HOME+" )
echo -e "resolution: $resolution\nsubresolution: $subresolution"

while true; do
	newtrack=$(mpc -f '%file%' current)
	if [ "$newtrack" != "$track" ]; then
		echo $(date '+%H:%M:%S') track changed to $newtrack

		track="$newtrack"
		track_file="$musicpath/$track"
		path="${track_file%/*}/"

		starttime=$(date +'%s.%N')
		if get_cover; then
			if same_cover; then
				echo $(date '+%H:%M:%S') "same cover art"
				# comment the line below if you don't want a notification on song change
				dunstify -u low --replace=169 -I "$cover_file" "$(mpc current)"
			else
				if [ "$cover_file" == '/tmp/embedded_cover.jpg' ]; then
					mv /tmp/new_embedded_cover.jpg /tmp/embedded_cover.jpg
				fi
				# comment the line below if you don't want a notification on song change
				dunstify -u low --replace=169 -I "$cover_file" "$(mpc current)"
				set_wallpaper
			fi
		else
			dunstify -u high --replace=169 "TRACK ADDED TO THE broken.txt"
			feh --no-fehbg --bg-center "$1"
		fi
		previous_cover_file="$cover_file"
		echo took $(echo "scale=6;$(date +'%s.%N')-$starttime" | bc)s
	fi
	mpc idle > /dev/null
done
